"""
Django settings for hemisphere_problem project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
import mongoengine

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '=91k5h2j6&-v7)ldfe)@k!g+#tfc775=tny(%1#p9jf)_0$16_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mongodbforms',
    'mongoadmin',
    'mongoengine.django.mongo_auth',
    'mongoadmin.auth',
    'django.contrib.admin',
    'rest_framework',
    'rest_framework_mongoengine',
    # 'account.apps.AccountConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hemisphere_problem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hemisphere_problem.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

MONGODB_USER = ''
MONGODB_PASSWD = ''
MONGODB_HOST = 'localhost'
MONGODB_PORT = 51796
MONGODB_NAME = 'hemi_db'

mongoengine.connect(MONGODB_NAME, host=MONGODB_HOST, port=MONGODB_PORT, username=MONGODB_USER, password=MONGODB_PASSWD)

# _MONGODB_USER = 'pratik'
# _MONGODB_PASSWD = 'hemi1234'
# _MONGODB_HOST = 'localhost'
# _MONGODB_NAME = 'testDb'
# _MONGODB_DATABASE_HOST = \
#   'mongodb://%s:%s@%s/%s' \
#   % (_MONGODB_USER, _MONGODB_PASSWD, _MONGODB_HOST, _MONGODB_NAME)
#
# mongoengine.connect(_MONGODB_NAME, host=_MONGODB_DATABASE_HOST)

DATABASES = {
    'default': {
        'ENGINE': ''
    }
}

SESSION_ENGINE = 'mongoengine.django.sessions'

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    )
}

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

MONGOADMIN_OVERRIDE_ADMIN = True

AUTHENTICATION_BACKENDS = (
            'mongoengine.django.auth.MongoEngineBackend',
    #'django_mongoengine.mongo_auth.backends.MongoEngineBackend',
)

AUTH_USER_MODEL = 'mongo_auth.MongoUser'    #'account.models.User'

MONGOENGINE_USER_DOCUMENT = 'mongoengine.django.auth.User'

SESSION_SERIALIZER = 'mongoengine.django.sessions.BSONSerializer'
